from pydantic import BaseModel
from typing import List, Optional

class DOMElement(BaseModel):
    id: str  # Unique identifier generated by the extension
    text: str
    tagName: str
    url: str

class AnalyzeRequest(BaseModel):
    elements: List[DOMElement]

class PredictionResult(BaseModel):
    id: str
    is_dark_pattern: bool
    dark_pattern_class: int  # 0: None, 1: Low-Risk, 2: High-Risk
    dark_pattern_conf: float
    is_phishing: bool
    phishing_conf: float
    explanation: str
    category: str  # Rule-based or ML category name (e.g., 'Urgency', 'Misdirection')

class AnalyzeResponse(BaseModel):
    results: List[PredictionResult]
    overall_risk_score: float
